### ISSUE TITLE
Rake emojione did not work.

### ISSUE THREAD

**Issue by CraneWing** [dimelo/emojione-rails#1]
I added to my Gemfile and typed "rake emojione," as instructed. The response wasn't installation of the images, but instead "The syntax of the command is incorrect."

**Comment by nel** [comment]
Hello,

Are you are running on windows ?

**Comment by CraneWing** [comment]
Yes, Win 7.

**Comment by nel** [comment]
Rake task was POSIX only, this is now crossplatform.

It should be fixed in dimelo/emojione-rails@70991d7a797ea7e I released Gem under 0.0.5

**Comment by CraneWing** [comment]
Thanks for the fix; it works fine now.
